cart/urls.py
from django.conf.urls import url
from cart import views
from django.conf.urls.static import static
from django.conf import settings
app_name = "cart"

urlpatterns = [
    url(r'^cart_add/(\d+)/$',views.cart_add,name='cart_add'),
    url(r'^cart_remove/(\d+)/$',views.cart_remove,name='cart_remove'),
    url(r'^cart_detail/$',views.cart_detail,name='cart_detail'),
]

mystore/urls.py
from django.contrib import admin
from django.urls import path
from mystore import views
from django.conf.urls import url

app_name = "mystore"

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^product_detail/(\d+)/$', views.product_detail, name='product_detail'),
    url(r'^dang_nhap/$', views.dang_nhap, name="dang_nhap"),
    url(r'^dang_xuat/$', views.dang_xuat, name="dang_xuat"),
    url(r'^dang_ky/$', views.dang_ky, name="dang_ky"),
    url(r'^contact/$', views.contact, name="contact"),
]

nha_thuoc/urls.py
from django.contrib import admin
from django.urls import path
from mystore import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls', namespace="orders")),
    path('',views.index,name='index'),
    path('mystore/', include('mystore.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from orders import views

app_name='orders'

urlpatterns = [
    url(r'^create/', views.order_create, name = 'order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]

class CardAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label= 'Số lượng', choices = PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required = False, widget = forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from mystore.models import Product
from .cart import Cart
from .forms import CardAddProductForm

# Create your views here.
@require_POST
def cart_add(request, product_id=None):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    form = CardAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product = product, quantity = cd['quantity'], update_quantity = cd['update'])
    print(cart)
    return redirect('cart:cart_detail')

def cart_remove(request, product_id=None):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CardAddProductForm(initial = {'quantity':item['quantity'], 'update': True } )
    return render(request, 'cart/cart_detail.html', {'cart':cart})

cart/templates/cart/cart_detail.html
{% extends "layout/base.html" %}

{% block body_block %}
    {% load staticfiles %}
    <div class="container"></div>
    <h1>Thông tin giỏ hàng</h1>
    <table class="table">
        <thead class="danger">
            <th>Sản phẩm</th>
            <th>Tên sản phẩm</th>
            <th>Số lượng</th>
            <th>Đơn giá (vnđ)</th>
            <th>Thành tiền (vnđ)</th>
            <th>Xóa</th>
        </thead>
        <tbody>
            {% for item in cart %}
                <tr class="success">
                    <td>
                    <a href="{% url 'mystore:product_detail' item.product.pk%}" ><img src="{{item.product.image.url}}"></a>
                    </td>
                    <td>{{item.product.name}}</td>
                    <td>
                    <form action = "{% url 'cart:cart_add' item.product.pk%}" method = "post">
                        {{item.update_quantity_form.quantity}}
                        {{item.update_quantity_form.update}}
                        <input type ="submit" value = "Cập nhật"/>
                        {% csrf_token %}
                    </form>
                    </td>
                    <td>{{item.fee}}</td>
                    <td>{{item.total_fee}}</td>
                    <td><a href="{% url 'cart:cart_remove' item.product.pk%}"> Xóa </a></td>
                </tr>
            {% endfor %}
            <tr class='total'>
                <td colspan="4"></td>
                <td class="num">Tổng: {{cart.get_total_fee}} vnđ</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'mystore:index' %}" class="btn btn-success">Tiếp tục mua hàng</a>
        <a href="{% url 'orders:order_create'%}" class="btn btn-success">Thanh toán</a>
    </p>
    </div>
{% endblock %}