cart/urls.py
from django.conf.urls import url
from cart import views
from django.conf.urls.static import static
from django.conf import settings
app_name = "cart"

urlpatterns = [
    url(r'^cart_add/(\d+)/$',views.cart_add,name='cart_add'),
    url(r'^cart_remove/(\d+)/$',views.cart_remove,name='cart_remove'),
    url(r'^cart_detail/$',views.cart_detail,name='cart_detail'),
]

mystore/urls.py
from django.contrib import admin
from django.urls import path
from mystore import views
from django.conf.urls import url

app_name = "mystore"

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^product_detail/(\d+)/$', views.product_detail, name='product_detail'),
    url(r'^dang_nhap/$', views.dang_nhap, name="dang_nhap"),
    url(r'^dang_xuat/$', views.dang_xuat, name="dang_xuat"),
    url(r'^dang_ky/$', views.dang_ky, name="dang_ky"),
    url(r'^contact/$', views.contact, name="contact"),
]

nha_thuoc/urls.py
from django.contrib import admin
from django.urls import path
from mystore import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls', namespace="orders")),
    path('',views.index,name='index'),
    path('mystore/', include('mystore.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mystore/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=264,unique=True)
    fee = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to = "images/")
    
    def __str__(self):
        return str(self.name)

class M_Khach_hang(models.Model):
    ho_ten = models.CharField(max_length=264,blank=False)
    ten_dang_nhap = models.CharField(max_length=50,blank=False)
    mat_khau = models.CharField(max_length=100,blank=False)
    phone = models.CharField(max_length=264,blank=False)
    email = models.EmailField(max_length=264,blank=False)
    dia_chi = models.TextField(max_length=264,blank=False)

    def __str__(self):
        return str(self.ho_ten)

    class Meta:
        db_table=u'Khachhang'

class Contact(models.Model):
    ho_ten = models.CharField(max_length = 264, blank = False)
    phone = models.CharField(max_length = 20)
    email = models.EmailField(blank = False)
    noi_dung = models.TextField()

    def __str__(self):
        return self.ho_ten
        
    class Meta:
        db_table=u'Contact'

mystore/forms.py
from django import forms
from .models import M_Khach_hang, Contact

class FormDangNhap():
    ten_dang_nhap = forms.CharField(max_length=100)
    mat_khau = forms.CharField(max_length=100)

class FormDangKy(forms.ModelForm):
    ho_ten = forms.CharField(max_length=264)
    ten_dang_nhap = forms.CharField(max_length=50)
    mat_khau = forms.CharField(widget=forms.PasswordInput())
    confirm = forms.CharField(widget=forms.PasswordInput())
    phone = forms.CharField(max_length=100)
    email = forms.EmailField()
    dia_chi = forms.CharField()

    class Meta:
        model = M_Khach_hang
        fields = ['ho_ten','ten_dang_nhap','mat_khau','phone','dia_chi']

class FormContact(forms.ModelForm):
    ho_ten = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=20)
    email = forms.EmailField()
    noi_dung = forms.Textarea()

    class Meta:
        model = Contact
        fields = ['ho_ten','phone','email', 'noi_dung']

mystore/views.py
from django.shortcuts import render
from mystore.models import Product, M_Khach_hang
from cart.forms import CardAddProductForm
from mystore import forms
from django.shortcuts import redirect
from django.contrib.auth.hashers import PBKDF2PasswordHasher
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def index(request):
    username=''
    if request.session.has_key('username'):
        username = request.session['username']
    pro_list = Product.objects.all()
    paginator = Paginator(pro_list, 4)
    page_number = request.GET.get("page")

    try:
        contacts = paginator.page(page_number)
    except PageNotAnInteger:
        # Nếu page_number không thuộc kiểu integer, trả về page đầu tiên
        contacts = paginator.page(1)
    except EmptyPage:
        # Nếu page không có item nào, trả về page cuối cùng
        contacts = paginator.page(paginator.num_pages)
    print(contacts)

    return render(request, "mystore/index.html", {"products":contacts,'username':username})

def product_detail(request, id=None):
    product = Product.objects.get(pk=id)
    cart_product_form = CardAddProductForm()
    return render(request, 'mystore/product_detail.html', context= {'product': product, 'cart_product_form': cart_product_form})

def dang_nhap(request):
    err = ''
    hasher = PBKDF2PasswordHasher()
    if request.method=="POST":
        _ten = request.POST.get('ten_dang_nhap')
        _mat_khau = hasher.encode(request.POST.get('mat_khau'),'123')
        kh = M_Khach_hang.objects.filter(ten_dang_nhap=_ten, mat_khau=_mat_khau)
        if kh.count()>0:
            request.session['username'] = kh[0].ho_ten
            err = 'Da luu khach hang vao session'
            return redirect('mystore:index')
        else:
            err = 'Dang nhap không thành công'
    return render(request, 'mystore/dang_nhap.html', {'err':err})

def dang_xuat(request):
    if request.session.has_key("username"):
        del request.session['username']
    return redirect('mystore:index')

def dang_ky(request):
    registered = False
    if request.method == "POST":
        form_user = forms.FormDangKy(request.POST, M_Khach_hang)
        #####################################################
        hasher = PBKDF2PasswordHasher()
        # Them validation cho form
        if form_user.is_valid() and form_user.cleaned_data['mat_khau'] == form_user.cleaned_data['confirm']:
            request.POST._mutable = True
            post = form_user.save(commit=False)
            post.ho_ten = form_user.cleaned_data['ho_ten']
            post.ten_dang_nhap = form_user.cleaned_data['ten_dang_nhap']
            ###########################################################
            post.mat_khau = hasher.encode(form_user.cleaned_data['mat_khau'],'123')
            post.email = form_user.cleaned_data['email']
            post.phone = form_user.cleaned_data['phone']
            post.dia_chi = form_user.cleaned_data['dia_chi']
            post.save()
            print('Da ghi user vao CSDL')
            registered = True
        elif form_user.cleaned_data['mat_khau'] != form_user.cleaned_data['confirm']:
            form_user.add_err('confirm','The password not match')
            print('Password and password confirm not match')
    else:
        form_user = forms.FormDangKy()

    return render(request, "mystore/registration.html", {'user_form':form_user, 'registered': registered})


def contact(request):
    registered = False
    if request.method == "POST":
        form_contact = forms.FormContact(data = request.POST)
        if form_contact.is_valid():
            register = form_contact.save()
            register.save()
            registered = True
        else:
            print(form_contact.errors)
    else:
        form_contact = forms.FormContact()
    return render(request, "mystore/contact.html",{'contact_form':form_contact,'registered': registered})

mystore/templates/mystore/contact.html
<!DOCTYPE html>
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="container-fluid">
    <div class="row">
        <div>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.1324536685306!2d106.67630031419394!3d10.80116599230477!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528d7880bb05f%3A0xfdfcf778ce7aea8d!2zNDI5LzQwIE5ndXnhu4VuIEtp4buHbSwgUGjGsOG7nW5nIDksIFBow7ogTmh14bqtbiwgSOG7kyBDaMOtIE1pbmgsIFZp4buHdCBOYW0!5e0!3m2!1svi!2s!4v1544924546094" width="1500" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            <br />
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-1">
            <h4>Địa chỉ liên hệ:</h4>
            <p class="block-author"> Công ty TNHH Diamond </p>
            <p>429/40 Nguyễn Kiệm, Phường 9, Quận Phú Nhuận, Tp.HCM</p>
            <p>Phone: 08.2456.321</p>
            <p>Fax: 08.2456.321</p>
            <em class="block-author">Email: diamond_treasure@gmail.com </em> <br>
        </div>
        <div class="col-lg-5">
            <div class="feedback-form">    
                <div id="contact-response"></div>    
                {% if registered %}
                    <h3>Cảm ơn bạn đã gửi ý kiến/ thông tin liên hệ</h3>
                {% else %}
                    <table>
                    <form method="post" id="contact-form">
                        <fieldset>
                        {% csrf_token %}
                        {% for field in contact_form%}
                            <tr><td>
                            <div class="form-group form-groupfullname">
                            <label class="control-label" for="fullname">{{field.label}}</label>
                            </div></td>
                            <td>
                            <div>
                            {{field}}
                            </div></td>
                        {% endfor%}
                        <tr><td colspan="2" align="center">
                            <input type="submit" class="btn btn-success" value="Gửi liên hệ">
                            </td></tr>
                            </fieldset>
                        </form>
                    </table>
                {% endif%}
            </div> 
        </div>
    </div>
</div>
{% endblock %}

mystore/templates/mystore/dang_nhap.html
<!DOCTYPE html>
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block body_block %}
<form class="form-signin" method="POST">
    {% csrf_token %}
      <img class="mb-4" src="{% static 'imgage/diamond.png'%}" alt="" width="72" height="72">
      <h2 class="h3 mb-3 font-weight-normal">Tiến hành đăng nhập hay <a class="link" href="{% url 'mystore:dang_ky'%}" style="color:red">Đăng ký</a></h2>
      <label for="inputEmail" class="sr-only">Tên đăng nhập</label>
      <input type="text" name="ten_dang_nhap" class="form-control" placeholder="Username" required autofocus>
      <label for="inputPassword" class="sr-only">Mật khẩu</label>
      <input type="password" name="mat_khau" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Ghi nhớ lần sau
        </label>
      </div>
      <button class="btn btn-lg btn-success btn-block" type="submit">Đăng nhập</button>
      <p class="mt-5 mb-3 text-muted">{{err}}</p>
    </form>
{% endblock %}

mystore/templates/mystore/index.html
<!DOCTYPE html>
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class='container-fluid'>
    <div class = 'row'>
        <div class='col-md-12'>
            <a class="navbar-brand"><h1><span>Danh sách sản phẩm</span></h1></a>
        </div>
    </div>
</div>
<div class='container-fluid'>
    <div class = 'row'>
        <div class='col-md-12'>
            <!-- Page Features -->
            <div class="row text-center">
                {% if products %}
                    {% for value in products %}
                        <div class="col-md-3 mb-4">
                            <div class="card">
                                <img class="card-img-top" src="{{value.image.url}}" alt="{{value.name}}">
                                <div class="card-body">
                                    <h4 class="card-title">{{value.name}}</h4>
                                    <p class="card-text">{{value.description}}<br/>{{value.fee}} vnđ</p>
                                </div>
                                <div>
                                    <a href="{% url 'mystore:product_detail' value.pk%}" class='btn btn-success' style="float: center;" > Xem thêm </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif%}
            </div>
            <ul class="pagination">
                <li class="step-links">
                    {% if products.has_previous %}
                        <a href="?page={{ products.previous_page_number }}">Previous</a>
                    {% endif %}
                </li>

                <span class="current">
                    Page {{ products.number }} of {{ products.paginator.num_pages }}.
                </span>

                <li>
                    {% if products.has_next %}
                        <a href="?page={{ products.next_page_number }}">Next</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

mystore/templates/mystore/product_detail.html
<!DOCTYPE html>
{% extends "layout/base.html" %}
{% block body_block %}
    {% load staticfiles %}
    <!-- Page Features -->
        <div class="row text-center">
            {% if product %}
                <div class="container">
                    <div class="card">
                        <img class="img-responsive" src="{{product.image.url}}"
                        alt="{{product.name}}" width="350" height="350"/>
                        <div class="card-body">
                            <h4 class="card-title">{{product.name}}</h4>
                            <p class="card-text">{{product.description}}<br/>{{product.fee}} vnđ</p>
                        </div>
                    <div>
                        <form action="{% url 'cart:cart_add' product.pk%}" method="post">
                            {{cart_product_form}}
                            {% csrf_token %}
                            <div class="card-footer" >
                            <input type="submit" value = "Thêm vào giỏ hàng" class="btn btn-primary">
                            </div>
                        </form>
                    </div>
                    </div>
                </div>
            {% endif%}
        </div>
{% endblock %}

mystore/templates/mystore/registration.html
{% extends "layout/base.html" %}

{% load staticfiles %}
{% block body_block %}
    <div class="container">
    {% if registered %}
        <h3>Bạn đã đăng ký thành công.</h3>
    {% else %}
        <h3>Điền vào form đăng ký</h3>
        <form method="POST" enctype="multipart/form-data">
        <table>

        {% for field in user_form %}
            <tr><td>{{field.label}} </td>
            <td>{{field}}</td></tr>
        {% endfor %}

        {% csrf_token %}

        <tr><td colspan='2' align="center">
        <input type="submit" class="btn btn-success" value="Đăng ký">   
        </td></tr>
        </table>
        </form>

    </div>
    {% endif %}
    </div>
{% endblock %}