cart/urls.py
from django.conf.urls import url
from cart import views
from django.conf.urls.static import static
from django.conf import settings
app_name = "cart"

urlpatterns = [
    url(r'^cart_add/(\d+)/$',views.cart_add,name='cart_add'),
    url(r'^cart_remove/(\d+)/$',views.cart_remove,name='cart_remove'),
    url(r'^cart_detail/$',views.cart_detail,name='cart_detail'),
]

mystore/urls.py
from django.contrib import admin
from django.urls import path
from mystore import views
from django.conf.urls import url

app_name = "mystore"

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^product_detail/(\d+)/$', views.product_detail, name='product_detail'),
    url(r'^dang_nhap/$', views.dang_nhap, name="dang_nhap"),
    url(r'^dang_xuat/$', views.dang_xuat, name="dang_xuat"),
    url(r'^dang_ky/$', views.dang_ky, name="dang_ky"),
    url(r'^contact/$', views.contact, name="contact"),
]

nha_thuoc/urls.py
from django.contrib import admin
from django.urls import path
from mystore import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls', namespace="orders")),
    path('',views.index,name='index'),
    path('mystore/', include('mystore.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout/base.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}

{% block head_title %}
    {% include 'layout/head_title.html' %}
{% endblock  %}

<body>

{% block  header %}
    {% include 'layout/header.html' %}
{% endblock  %}

{% block body_block %}

{% endblock  %}

{% block footer %}
    {% include 'layout/footer.html' %}
{% endblock  %}

{% block js_script %}
    {% include 'layout/js_script.html' %}
{% endblock  %}

</body>

templates/layout/footer.html
	<footer>
		<div class="footer">
			<div class="container">
				<div class="social-icon">
					<div class="col-md-4">
						<ul class="social-network">
							<li><a href="#" class="fb tool-tip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#" class="twitter tool-tip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#" class="gplus tool-tip" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#" class="linkedin tool-tip" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
							<li><a href="#" class="ytube tool-tip" title="You Tube"><i class="fa fa-youtube-play"></i></a></li>
						</ul>	
					</div>
				</div>
				
				<div class="col-md-4 col-md-offset-4">
					<div class="copyright">
						&copy; June  2015 by <a target="_blank" href="/admin" title="Liêm Edited">Go to admin</a>. All Rights Reserved.
					</div>
                    <!-- 
                        All links in the footer should remain intact. 
                        Licenseing information is available at: http://bootstraptaste.com/license/
                        You can buy this theme without footer links online at: http://bootstraptaste.com/buy/?theme=Company
                    -->
				</div>						
			</div>
			
			<div class="pull-right">
				<a href="#home" class="scrollup"><i class="fa fa-angle-up fa-3x"></i></a>
			</div>		
		</div>
	</footer>

templates/layout/head_title.html
{% load staticfiles %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %} {% endblock  %} </title>

    <!-- Bootstrap -->
    <link href="{% static 'css_js/dist/css/bootstrap.min.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'Company/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'Company/css/animate.css' %}">
	<link href="{% static 'Company/css/prettyPhoto.css' %}" rel="stylesheet">
	<link href="{% static 'Company/css/style.css' %}" rel="stylesheet" />	
    <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

templates/layout/header.html
{% load staticfiles %}
	<header>		
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="{% url 'mystore:index' %}"><h1><span>Diamond </span>Shop</h1></a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'mystore:index' %}">Trang chủ <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Tư vấn</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">BLOG</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'mystore:contact' %}">Liên hệ</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Về chúng tôi</a>
					</li>
					<li class="nav-item">
					{% if username %}
						<a class="nav-link" href="{% url 'mystore:dang_xuat' %}">Xin chào, {{username}}</span></a>
					{% else %}
						<a class="nav-link" href="{% url 'mystore:dang_nhap' %}">Đăng nhập</span></a>
					{% endif %}	
					</li>
					</ul>
				<ul class="navbar-nav text-right">
					<li class="nav-item">
						<a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'cart:cart_detail'%}">Giỏ hàng</a>
					</li>
					<li class="nav-item">
						{% if cart %}
						<a class="nav-link" href="{% url 'cart:cart_detail'%}">
						Giỏ hàng có {{cart|length}} sản phẩm , VNĐ: {{cart.get_total_fee}}</a>
						{% endif %}
					</li>
				</ul>
			</div>
		</nav>	
		<div class='container-fluid'>
			<div class = 'row'>
				<div class='col-md-12'>
					<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
						<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
						<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
						<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
					</ol>
					<div class="carousel-inner">
						<div class="carousel-item active">
						<img class="d-block w-100" src="{% static "images/slide_1.jpg" %}" alt="First slide">
						</div>
						<div class="carousel-item">
						<img class="d-block w-100" src="{% static "images/slide_2.png" %}" alt="Second slide">
						</div>
						<div class="carousel-item">
						<img class="d-block w-100" src="{% static "images/slide_3.jpg" %}" alt="Third slide">
						</div>
					</div>
					<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
					</div>
				</div>
			</div>
		</div>
	</header>

templates/layout/js_script.html
    {% load staticfiles %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="{% static 'css_js/js/jquery-3.3.1.min.js' %}"></script>	
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'css_js/dist/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'Company/js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'Company/js/jquery.isotope.min.js' %}"></script>  
	<script src="{% static 'Company/js/wow.min.js' %}"></script>
	<script src="{% static 'Company/js/functions.js' %}"></script>
    <script src="{% static 'css_js/assets/js/vendor/popper.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->